import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { Navbar } from "@/components/navbar";
import localFont from 'next/font/local';
import AuthenticationProvider from "@/Context/Authentication";


const Chillax = localFont({
  src: [
    {
      path: '../../public/fonts/Chillax-Variable.ttf',
      weight: '200 700',
      style: 'normal',
    },
  ],
  variable: '--font-chillax',
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Veerath | News",
  description: "Generated by create next app",
  icons: {
    icon: "/logo.png",
  },
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className={`${Chillax.variable}`}
    >
      <AuthenticationProvider>
      <html
        lang="en"
        suppressHydrationWarning
        className={`${Chillax.variable}`}
      >
        <body className="antialiased scroll-smooth bg-zinc-50 dark:bg-zinc-950">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Navbar />
            <Toaster />
            {children}
          </ThemeProvider>
        </body>
      </AuthenticationProvider>
    </html>
  );
}